### ISSUE TITLE
How do I run this thing?

### ISSUE THREAD

**Issue by theronic** [mikera/magic#13]
OMG this is great how do I run it?

**Comment by mikera** [comment]
A few options:
- You can use it directly as a library from Java. See the tests for many examples.
- You can (experimental) use it via a Clojure nREPL using https://github.com/mikera/enchant
- You can launch a REPL from the command line with `magic repl` (tested only on Windows, but should be trivial to modify `magic.bat` for Unix

Note that Magic is still very experimental! Any feedback / PRs much appreciated!

**Comment by theronic** [comment]
What command should I run to compile magic? (I'm not a Java guy, but I think `javac` is involved. Am running OSX.)

IntelliJ picked up some things, but I don't see jar output in target folder.

**Comment by mikera** [comment]
There's probably an easy way to compile using IntelliJ but I'm not too familar with that. By default Magic is build using Maven, you can build the combined jar file with:

`mvn -Dmaven.test.skip=true install`

This will give you a copmpiled jar file in the `target` directory which you can then run with:

`java -jar target/magic.jar`

If you want a REPL, use:

`java -jar target/magic.jar repl`
