### ISSUE TITLE
Metadata?

### ISSUE THREAD

**Issue by mikera** [mikera/magic#5]
Consider how metadata should be handled in Magic

Considerations:
- Not all objects in forms can support metadata, given presence of Java literal values. Ubiquitous wrapping might be an option, but this introduces complexity and overhead that may not be desirable.
- Possible that metadata should be associated with `Slot`s
- Needed in some cases for compatibility with Clojure

**Comment by arrdem** [comment]
No. Drop this feature. Metadata is a magical untyped bag of objects you can bolt onto ~*~some~*~ things. Its failure modes aren't obvious, and simply boxing everything in what is effectively an `IMeta<obj, Map meta>` cons and adding checkcast unboxes everywhere you do interop or typecasts is likely unreasonable.

**Comment by mikera** [comment]
Thanks for the input - I had a suspicion that might be the case!

**Comment by mikera** [comment]
Currently decided to drop metadata as a feature in general.

However note that we still currently use metadata (as an implementation detail) for AST nodes, where it seems to be very useful for things like source mapping etc. This seems to be a good compromise so far.
